language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: brennan.barker
  password:
    secure: YK4w4rcqv34kwliIPKp7WbzWby2wyeuzDS1W+phyuTxTJXnIq+gKd1PJ+3qnd1cLtIULBqJYg2bNuYPXad8vFVtJ2+KSte9pdSDCPAKqVaclPSDWNejsOq9AkWHrLwGv3IIpTFxWld5yc+sQsEl6OATHpuXSB7QydeBImbzoREydcdsXbW3/bb/p0cdqrcwZuLVuQxTA4VaUnx7HvC1Wd1KXk54bvaQ575qTzWU9jk7OzzSjxzpVqM2FV1JvonlwBhgN9TOIjEv2BlS7eylf/oZSXdKkJnDtI9vPUEUIgElZ6tn6rJxmQBAciX37dfQliu4gLcunpjvghpcwjZVOeMqq6l19yvm7Sp5X6nfCstcURAbvS0isficXZkFnqbf605/JO3SZ6rPGH7ZN21Y476xNHKLyKuhZQl/FWeVp+vx5Gc7rAHlepnQvuIuo9WJOUZpYEzOy5HlxAPLnEiZQu1J7sp30I35i7jItepJeGNPWh00dTfOwMVdb3BndCuil8aJjRU0ye4p3Xqq6Tz78Ar1waVMTjDN5+oDxoEWsXKydybRtdT9pQZsSjMGVFi9g0nLpPnAoCHw8pzrEN7AzfztUhXYph5GHDlYfQPle7/w/VCLBhl7QkAb+Dftr7GDB34gziivfQ7LwrrvPQ5Q6QCBUW2IBGVF2mmf+MtXwe2A=
  on:
    tags: true
    repo: brennan.barker/kune
    python: 3.8
